[package]
name = "berlin-ubahn-d-f"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[patch.crates-io]
lotussim-script = { path = "../../script-rs/lotus-script" }
lotussim-script-sys = { path = "../../script-rs/lotus-script-sys" }
lotus-extra = { path = "../../lotus-extra" }

[dependencies]
lotus-extra = "0.3.3"
lotussim-script = "*"
